"""updated ChatMessage with message_type, message_metadata and parent message

Revision ID: 0b320c8c8687
Revises: f83683539d95
Create Date: 2025-06-04 17:52:51.127967

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b320c8c8687"
down_revision = "f83683539d95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    message_type_enum = sa.Enum("message", "tool_call", "tool_response", name="messagetypeenum")
    message_type_enum.create(op.get_bind())

    op.add_column("chat_messages", sa.Column("message_type", message_type_enum, nullable=False))
    op.add_column("chat_messages", sa.Column("message_metadata", sa.JSON(), nullable=True))
    op.add_column("chat_messages", sa.Column("parent_message_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "chat_messages", "chat_messages", ["parent_message_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    op.drop_column("chat_messages", "parent_message_id")
    op.drop_column("chat_messages", "message_metadata")
    op.drop_column("chat_messages", "message_type")

    # Drop the enum type
    message_type_enum = sa.Enum("message", "tool_call", "tool_response", name="messagetypeenum")
    message_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
