"""updated query table, added query version, query runs tables

Revision ID: 37683b5f35ad
Revises: 5b25217cc04d
Create Date: 2025-06-06 13:02:09.834686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37683b5f35ad'
down_revision = '5b25217cc04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sql', sa.String(), nullable=False),
    sa.Column('save_trigger', sa.Enum('manual', 'run', 'ai', 'on_exit', name='querytriggerenum'), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_message', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('query_version_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['query_version_id'], ['query_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('queries', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'queries', 'users', ['created_by'], ['id'])
    op.drop_column('queries', 'query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'created_by')
    op.drop_table('query_runs')
    op.drop_table('query_versions')
    # ### end Alembic commands ###
