"""added soft delete

Revision ID: 38558bdf3959
Revises: c29789fd9477
Create Date: 2025-06-12 13:56:35.891570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38558bdf3959'
down_revision = 'c29789fd9477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('llms', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('queries', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sources', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'deleted_at')
    op.drop_column('sources', 'deleted_at')
    op.drop_column('queries', 'deleted_at')
    op.drop_column('llms', 'deleted_at')
    op.drop_column('chat_sessions', 'deleted_at')
    # ### end Alembic commands ###
