"""removed worker

Revision ID: 50351ead9036
Revises: ef44ce32bce2
Create Date: 2025-06-28 10:53:07.618648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50351ead9036'
down_revision = 'ef44ce32bce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('host', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('workers_source_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workers_pkey'))
    )
    # ### end Alembic commands ###
