"""removed user and worksapce

Revision ID: 5303c7058643
Revises: 38558bdf3959
Create Date: 2025-06-12 19:07:27.624271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5303c7058643'
down_revision = '38558bdf3959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_messages_user_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_sessions_workspace_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_constraint(op.f('llms_workspace_id_fkey'), 'llms', type_='foreignkey')
    op.drop_constraint(op.f('queries_created_by_fkey'), 'queries', type_='foreignkey')
    op.drop_constraint(op.f('query_runs_created_by_fkey'), 'query_runs', type_='foreignkey')
    op.drop_constraint(op.f('query_versions_created_by_fkey'), 'query_versions', type_='foreignkey')
    op.drop_constraint(op.f('sources_workspace_id_fkey'), 'sources', type_='foreignkey')
    op.drop_constraint(op.f('workers_workspace_id_fkey'), 'workers', type_='foreignkey')
    # drop columns
    op.drop_column('chat_messages', 'user_id')
    op.drop_column('chat_sessions', 'workspace_id')
    op.drop_column('llms', 'workspace_id')
    op.drop_column('queries', 'created_by')
    op.drop_column('query_runs', 'created_by')
    op.drop_column('query_versions', 'created_by')
    op.drop_column('sources', 'workspace_id')
    op.drop_column('workers', 'workspace_id')

    # drop tables
    op.drop_table('workspace_users')
    op.drop_table('users')
    op.drop_table('workspaces')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('workers_workspace_id_fkey'), 'workers', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('sources', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sources_workspace_id_fkey'), 'sources', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('query_versions', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('query_versions_created_by_fkey'), 'query_versions', 'users', ['created_by'], ['id'])
    op.add_column('query_runs', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('query_runs_created_by_fkey'), 'query_runs', 'users', ['created_by'], ['id'])
    op.add_column('queries', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('queries_created_by_fkey'), 'queries', 'users', ['created_by'], ['id'])
    op.add_column('llms', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('llms_workspace_id_fkey'), 'llms', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('chat_sessions', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chat_sessions_workspace_id_fkey'), 'chat_sessions', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('chat_messages', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chat_messages_user_id_fkey'), 'chat_messages', 'users', ['user_id'], ['id'])
    op.create_table('workspace_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'editor', 'viewer', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('workspace_users_user_id_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_users_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_users_pkey'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workspaces_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    # ### end Alembic commands ###
