"""add sql_query column to chat_messages

Revision ID: 5b25217cc04d
Revises: 0b320c8c8687
Create Date: 2025-06-05 13:21:30.422851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b25217cc04d'
down_revision = '0b320c8c8687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('sql_query', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'sql_query')
    # ### end Alembic commands ###
