"""added is_ephemeral and preview_key to query model, added modifiers to query runs

Revision ID: c29789fd9477
Revises: 1e7f412ea9d0
Create Date: 2025-06-09 16:39:00.934203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c29789fd9477'
down_revision = '1e7f412ea9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('is_ephemeral', sa.Boolean(), nullable=True))
    op.add_column('queries', sa.Column('preview_key', sa.String(), nullable=True))
    op.add_column('query_runs', sa.Column('modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_runs', 'modifiers')
    op.drop_column('queries', 'preview_key')
    op.drop_column('queries', 'is_ephemeral')
    # ### end Alembic commands ###
