"""added workepace_id to worker table

Revision ID: c7e90936f97a
Revises: 28ae5feaa852
Create Date: 2025-05-28 14:35:08.151530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e90936f97a'
down_revision = '28ae5feaa852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'workers', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_column('workers', 'workspace_id')
    # ### end Alembic commands ###
