"""added status and datetimes to query run

Revision ID: cca82ef3a3c1
Revises: 50351ead9036
Create Date: 2025-07-12 16:53:03.975249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca82ef3a3c1'
down_revision = '50351ead9036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_runs', sa.Column('status', sa.String(), nullable=True))
    op.add_column('query_runs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('query_runs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_runs', 'completed_at')
    op.drop_column('query_runs', 'updated_at')
    op.drop_column('query_runs', 'status')
    # ### end Alembic commands ###
