"""added context to chat messages, updated message to use query and version

Revision ID: ef44ce32bce2
Revises: 5303c7058643
Create Date: 2025-06-13 20:04:09.062196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef44ce32bce2'
down_revision = '5303c7058643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('query_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['query_version_id'], ['query_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('chat_sessions_source_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'source_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chat_sessions_source_id_fkey'), 'chat_sessions', 'sources', ['source_id'], ['id'])
    op.drop_table('chat_contexts')
    # ### end Alembic commands ###
