services:
  user-postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/init.sql
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - dribble-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  dribble-network:
    external: true
    name: dribble-network
  
volumes:
  user_postgres_data:
  